# Nombre del flujo de trabajo
name: Puesta a produccion

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  desplegar:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Verificar
        uses: actions/checkout@v4

      - name: Configurar NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci  #npm install

      - name: Construir
        run: npm run build

      - name: Configurar Github Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
